spring:
  profiles:
    active: localSecured
---
spring:
  profiles: local
  kafka:
    template:
      default-topic: LIBRARY-TOPIC
    producer:
      bootstrap-servers:
        - localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 5
        #retry.backoff.ms: 1000
---
spring:
  profiles: localSecured
  kafka:
    template:
      default-topic: LIBRARY-SECURED-TOPIC
    producer:
      bootstrap-servers:
        - localhost:9095, localhost:9096, localhost:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        trust-store-location: file:/Users/jongtenerife/bootworkspace/kafka-for-developers-using-spring-boot/ssl/client.truststore.jks
        trust-store-password: secret
        key-store-location: file:/Users/jongtenerife/bootworkspace/kafka-for-developers-using-spring-boot/ssl/client.keystore.jks
        key-store-password: secret
      properties:
        acks: all
        retries: 5
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:
        #retry.backoff.ms: 1000


library:
  topicBean: topicProducer
  topics:
    eventOne: LIBRARY-TOPIC-ONE
    eventTwo: LIBRARY-TOPIC-TWO
---