spring:
  profiles:
    active: localSecured

server:
  port: 8081

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
  kafka:
    template:
      default-topic: LIBRARY-TOPIC
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      group-id: group1
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 5
        retry.backoff.ms: 20

---
spring:
  profiles: localSecured
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
  kafka:
    template:
      default-topic: LIBRARY-SECURED-TOPIC
    consumer:
      bootstrap-servers: localhost:9095, localhost:9096, localhost:9097
      group-id: group1
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      ssl:
        trust-store-location: file:/Users/jongtenerife/bootworkspace/kafka-for-developers-using-spring-boot/ssl/client.truststore.jks
        trust-store-password: secret
        key-store-location: file:/Users/jongtenerife/bootworkspace/kafka-for-developers-using-spring-boot/ssl/client.keystore.jks
        key-store-password: secret
      properties:
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm: